CREATE USER TEST_A
IDENTIFIED BY NAV
DEFAULT TABLESPACE SEAWARE_DEVELOPMENT
TEMPORARY TABLESPACE TEMP;

CREATE TABLE TEST_A.CONTACT (
  ID         NUMBER(5) PRIMARY KEY,
  FIRST_NAME VARCHAR2(60)        NOT NULL,
  LAST_NAME  VARCHAR2(40)        NOT NULL,
  BIRTH_DATE DATE DEFAULT (sysdate),
  VERSION    NUMBER(3) DEFAULT 0 NOT NULL
);

ALTER TABLE TEST_A.CONTACT
  ADD CONSTRAINT UQ_CONTACT_1 UNIQUE (FIRST_NAME, LAST_NAME);

CREATE SEQUENCE TEST_A.CONTACT_ID_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TEST_A.CONTACT_ID
BEFORE INSERT ON TEST_A.CONTACT
FOR EACH ROW

  BEGIN
    SELECT TEST_A.CONTACT_ID_SEQ.nextval
    INTO :new.id
    FROM dual;
  END;
/

--DROP USER TEST_A;

CREATE USER TEST_B
IDENTIFIED BY NAV
DEFAULT TABLESPACE SEAWARE_DEVELOPMENT
TEMPORARY TABLESPACE TEMP;

CREATE TABLE TEST_B.CONTACT (
  ID         NUMBER(5) PRIMARY KEY,
  FIRST_NAME VARCHAR2(60)        NOT NULL,
  LAST_NAME  VARCHAR2(40)        NOT NULL,
  BIRTH_DATE DATE DEFAULT (sysdate),
  VERSION    NUMBER(3) DEFAULT 0 NOT NULL
);

ALTER TABLE TEST_B.CONTACT
  ADD CONSTRAINT UQ_CONTACT_1 UNIQUE (FIRST_NAME, LAST_NAME);

CREATE SEQUENCE TEST_B.CONTACT_ID_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TEST_B.CONTACT_ID
BEFORE INSERT ON TEST_B.CONTACT
FOR EACH ROW

  BEGIN
    SELECT TEST_B.CONTACT_ID_SEQ.nextval
    INTO :new.id
    FROM dual;
  END;
/

--DROP USER TEST_A;

-- select * from TEST_A.CONTACT;
-- select * from TEST_B.CONTACT;

GRANT SELECT ON sys.dba_pending_transactions TO TEST_A;
GRANT SELECT ON sys.pending_trans$ TO TEST_A;
GRANT SELECT ON sys.dba_2pc_pending TO TEST_A;
GRANT EXECUTE ON sys.dbms_system TO TEST_A;

GRANT SELECT ON sys.dba_pending_transactions TO TEST_B;
GRANT SELECT ON sys.pending_trans$ TO TEST_B;
GRANT SELECT ON sys.dba_2pc_pending TO TEST_B;
GRANT EXECUTE ON sys.dbms_system TO TEST_B;

GRANT CREATE SESSION TO TEST_A WITH ADMIN OPTION;
GRANT CREATE SESSION TO TEST_B WITH ADMIN OPTION;

ALTER USER TEST_A QUOTA 100M ON SEAWARE_DEVELOPMENT;
ALTER USER TEST_B QUOTA 100M ON SEAWARE_DEVELOPMENT;