CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(60) NOT NULL
  , LAST_NAME VARCHAR(40) NOT NULL
  , BIRTH_DATE DATE
  , PRIMARY KEY (ID)
);

ALTER TABLE CONTACT ADD CONSTRAINT UQ_CONTACT_1 UNIQUE (FIRST_NAME, LAST_NAME);

CREATE TABLE CONTACT_TEL_DETAIL (
    ID INT NOT NULL AUTO_INCREMENT
  , CONTACT_ID INT NOT NULL
  , TEL_TYPE VARCHAR(20) NOT NULL
  , TEL_NUMBER VARCHAR(20) NOT NULL
  , PRIMARY KEY (ID)
  , CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY (CONTACT_ID)
REFERENCES CONTACT (ID)
);

ALTER TABLE CONTACT_TEL_DETAIL ADD CONSTRAINT UQ_CONTACT_TEL_DETAIL_1 UNIQUE (CONTACT_ID, TEL_TYPE);
