CREATE TABLE CONTACT_AUDIT (
  ID                 INT         NOT NULL AUTO_INCREMENT
  ,
  FIRST_NAME         VARCHAR(60) NOT NULL
  ,
  LAST_NAME          VARCHAR(40) NOT NULL
  ,
  BIRTH_DATE         DATE
  ,
  VERSION            INT         NOT NULL DEFAULT 0
  ,
  CREATED_BY         VARCHAR(20)
  ,
  CREATED_DATE       TIMESTAMP
  ,
  LAST_MODIFIED_BY   VARCHAR(20)
  ,
  LAST_MODIFIED_DATE TIMESTAMP
  ,
  PRIMARY KEY (ID)
);

ALTER TABLE CONTACT_AUDIT
  ADD CONSTRAINT UQ_CONTACT_AUDIT_1 UNIQUE (FIRST_NAME, LAST_NAME);

CREATE TABLE CONTACT_AUDIT_H (
  ID                    INT         NOT NULL
  ,
  FIRST_NAME            VARCHAR(60) NOT NULL
  ,
  LAST_NAME             VARCHAR(40) NOT NULL
  ,
  BIRTH_DATE            DATE
  ,
  VERSION               INT         NOT NULL DEFAULT 0
  ,
  CREATED_BY            VARCHAR(20)
  ,
  CREATED_DATE          TIMESTAMP
  ,
  LAST_MODIFIED_BY      VARCHAR(20)
  ,
  LAST_MODIFIED_DATE    TIMESTAMP
  ,
  AUDIT_REVISION        INT         NOT NULL
  ,
  ACTION_TYPE           INT
  ,
  AUDIT_REVISION_END    INT
  ,
  AUDIT_REVISION_END_TS TIMESTAMP
  ,
  PRIMARY KEY (ID, AUDIT_REVISION)
);

ALTER TABLE CONTACT_AUDIT_H
  ADD CONSTRAINT UQ_CONTACT_AUDIT_H_1 UNIQUE (FIRST_NAME, LAST_NAME);

CREATE TABLE REVINFO (
  REVTSTMP BIGINT NOT NULL
  ,
  REV      INT    NOT NULL AUTO_INCREMENT
  ,
  PRIMARY KEY (REVTSTMP, REV)
);