CREATE TABLE CONTACT_AUDIT (
  ID                 INT         NOT NULL AUTO_INCREMENT
  ,
  FIRST_NAME         VARCHAR(60) NOT NULL
  ,
  LAST_NAME          VARCHAR(40) NOT NULL
  ,
  BIRTH_DATE         DATE
  ,
  VERSION            INT         NOT NULL DEFAULT 0
  ,
  CREATED_BY         VARCHAR(20)
  ,
  CREATED_DATE       TIMESTAMP
  ,
  LAST_MODIFIED_BY   VARCHAR(20)
  ,
  LAST_MODIFIED_DATE TIMESTAMP
  ,
  PRIMARY KEY (ID)
);

ALTER TABLE CONTACT_AUDIT
  ADD CONSTRAINT UQ_CONTACT_AUDIT_1 UNIQUE (FIRST_NAME, LAST_NAME);