DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CAR (
  ID               INT         NOT NULL AUTO_INCREMENT
  ,
  LICENSE_PLATE    VARCHAR(20) NOT NULL
  ,
  MANUFACTURER     VARCHAR(20) NOT NULL
  ,
  MANUFACTURE_DATE DATE        NOT NULL
  ,
  AGE              INT         NOT NULL DEFAULT 0
  ,
  VERSION          INT         NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
);

ALTER TABLE CAR
  ADD CONSTRAINT UQ_CAR_1 UNIQUE (LICENSE_PLATE);